### ISSUE TITLE
Cinematics FPS @ 30

### ISSUE THREAD

**Issue by DJKeterson** [MaxLastBreath/TOTK-DFPS#4]
Hey, not sure if intended or not but I noticed cinematics are locked to 30fps regardless if I have VSync on or off. I have set 60 fps in the mod .ini file.

![image](https://github.com/MaxLastBreath/TOTK-DFPS/assets/33098373/2b961091-27e8-492d-ba16-6e43dfbb2561)

**Comment by MaxLastBreath** [comment]
This is intended behavior.
