### ISSUE TITLE
Bloodmoon Cinematic Crash

### ISSUE THREAD

**Issue by anihavoc** [MaxLastBreath/TOTK-DFPS#5]
Getting a crash on first bloodmoon video cinematic using the default settings. Disabling DFPS++ allows for the cinematic to play correctly. Unsure if this effects other video cinematics as well as this is the first one played using DFPS++ (default 60 fps)

**Comment by MaxLastBreath** [comment]
Have you tried using UltraCam? This issue doesn't exist on UltraCam so i assume you are using an older version of the Optimizer?

**Comment by anihavoc** [comment]
I was using UltraCam up until 4K/2K mod came out recently and was recommended to use DFPS++ instead of DynamicFPS 1.5.5. Not using Optimizer and using Fayaz's Settings for Custom ultrawide Resolution/ Xbox UI. Those remained active and allowed the cinematic to play but had to disable DFPS++ as it was the one causing it. I tried disabling those other mods first to see if that was the issue but still had it freeze at cinematic load

**Comment by MaxLastBreath** [comment]
yeah im aware but the ultracam has DFPS and it shouldnt crash, if you are using the old version of optimizer with the DFPS++ it has that crash only on 1.1.2 :D

**Comment by anihavoc** [comment]
ah makes sense as I'm on still on 1.1.2 due to a mod, thank you for clarification!
